# Generated by Django 5.1.3 on 2024-11-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CountdownDate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateTimeField()),
            ],
        ),
    ]
